name       : gnome-games
version    : 3.28.0
release    : 5
source     :
    - https://download.gnome.org/sources/gnome-games/3.28/gnome-games-3.28.0.tar.xz : 64689b7b916345a790f3599b9127206ae055983a90c25bd1356e8827834ea200
license    : GPL-3.0
component  : games
summary    : Simple game launcher for GNOME
description: |
    Games is a GNOME application to browse your video games library and to easily pick and play a game from it
builddeps  :
    - pkgconfig(grilo-0.3)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libarchive)
    - pkgconfig(libevdev)
    - pkgconfig(libpulse)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(manette-0.2)
    - pkgconfig(retro-gtk-0.14)
    - pkgconfig(sqlite3)
    - pkgconfig(tracker-sparql-2.0)
    - vala
setup      : |
    %patch --verbose -p1 < $pkgfiles/0001-plugins-steam-Use-fallback-Steam-path-when-registry-.patch
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
