name       : gnome-games
version    : 3.26.1
release    : 4
source     :
    - https://download.gnome.org/sources/gnome-games/3.26/gnome-games-3.26.1.tar.xz : 38d8ee0bd05969dc32f70aacdafc8a27fc5e4865f2715a0e6748e2fe9fb8f311
license    : GPL-3.0
component  : games
summary    : Simple game launcher for GNOME
description: |
    Games is a GNOME application to browse your video games library and to easily pick and play a game from it
builddeps  :
    - pkgconfig(grilo-0.3)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libarchive)
    - pkgconfig(libevdev)
    - pkgconfig(libpulse)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(retro-gtk-0.12)
    - pkgconfig(sqlite3)
    - pkgconfig(tracker-sparql-2.0)
    - vala
setup      : |
    %patch --verbose -p1 < $pkgfiles/0001-plugins-steam-Use-fallback-Steam-path-when-registry-.patch
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
