name       : gnome-games
version    : 3.24.0.2
release    : 2
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/gnome-games/3.24/gnome-games-3.24.0.2.tar.xz : 99c5d1b6bdbb46a03c7075e9b48d61d61890a9cd0b6b0b25f93b0b5d51e60070
license    : GPL-3.0
component  : games
summary    : Simple game launcher for GNOME
description: |
    Games is a GNOME application to browse your video games library and to easily pick and play a game from it
builddeps  :
    - pkgconfig(grilo-0.3)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libarchive)
    - pkgconfig(libevdev)
    - pkgconfig(libpulse)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(retro-gtk-0.10)
    - pkgconfig(tracker-sparql-1.0)
    - vala
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
